In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\aashu\OneDrive\Desktop\Churn Prediction\data\raw_churn_data.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [6]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors= 'coerce')
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [7]:
# Rows where TotalCharges is missing
missing_total = df[df['TotalCharges'].isna()]
print(f"Missing TotalCharges rows: {len(missing_total)}")

# Show key columns for inspection
cols_to_show = ['customerID', 'tenure', 'MonthlyCharges', 'TotalCharges', 'Churn']
print(missing_total[cols_to_show].head(20))

Missing TotalCharges rows: 11
      customerID  tenure  MonthlyCharges  TotalCharges Churn
488   4472-LVYGI       0           52.55           NaN    No
753   3115-CZMZD       0           20.25           NaN    No
936   5709-LVOEQ       0           80.85           NaN    No
1082  4367-NUYAO       0           25.75           NaN    No
1340  1371-DWPAZ       0           56.05           NaN    No
3331  7644-OMVMY       0           19.85           NaN    No
3826  3213-VVOLG       0           25.35           NaN    No
4380  2520-SGTTA       0           20.00           NaN    No
5218  2923-ARZLG       0           19.70           NaN    No
6670  4075-WKNIU       0           73.35           NaN    No
6754  2775-SEFEE       0           61.90           NaN    No

In [8]:
## BEFORE FILLNA CHANGE
## ------
no_tenure = df[df['tenure'] == 0]
if missing_total.equals(no_tenure):
    print("All missing TotalCharges correspond to tenure of 0.")
print(no_tenure[cols_to_show].head(20))
## ------

print("\n=== NOW RUNNING FILLNA ===")
# Since these customers have no tenure, we can fill TotalCharges with 0
df['TotalCharges'] = df['TotalCharges'].fillna(0)
print(f"Missing TotalCharges after fill: {df['TotalCharges'].isna().sum()}")


## AFTER FILLNA CHANGE
## -----
no_tenure_updated = df[df['tenure'] == 0]
print("Updated no_tenure rows after fillna:")
no_tenure_updated[cols_to_show]
## ------


# no_tenure is snapshot of original df with total charges missing
# no_tenure_updated is snapshot of orignal df AFTER total charges fillna

All missing TotalCharges correspond to tenure of 0.
      customerID  tenure  MonthlyCharges  TotalCharges Churn
488   4472-LVYGI       0           52.55           NaN    No
753   3115-CZMZD       0           20.25           NaN    No
936   5709-LVOEQ       0           80.85           NaN    No
1082  4367-NUYAO       0           25.75           NaN    No
1340  1371-DWPAZ       0           56.05           NaN    No
3331  7644-OMVMY       0           19.85           NaN    No
3826  3213-VVOLG       0           25.35           NaN    No
4380  2520-SGTTA       0           20.00           NaN    No
5218  2923-ARZLG       0           19.70           NaN    No
6670  4075-WKNIU       0           73.35           NaN    No
6754  2775-SEFEE       0           61.90           NaN    No

=== NOW RUNNING FILLNA ===
Missing TotalCharges after fill: 0
Updated no_tenure rows after fillna:

      customerID  tenure  MonthlyCharges  TotalCharges Churn
488   4472-LVYGI       0           52.55           0.0    No
753   3115-CZMZD       0           20.25           0.0    No
936   5709-LVOEQ       0           80.85           0.0    No
1082  4367-NUYAO       0           25.75           0.0    No
1340  1371-DWPAZ       0           56.05           0.0    No
3331  7644-OMVMY       0           19.85           0.0    No
3826  3213-VVOLG       0           25.35           0.0    No
4380  2520-SGTTA       0           20.00           0.0    No
5218  2923-ARZLG       0           19.70           0.0    No
6670  4075-WKNIU       0           73.35           0.0    No
6754  2775-SEFEE       0           61.90           0.0    No

In [9]:
churn_count = df['Churn'].value_counts()
churn_percentage = df['Churn'].value_counts(normalize=True) *100
churn_df = pd.DataFrame({'Count': churn_count, 'Percentage': churn_percentage})
churn_df

       Count  Percentage
Churn
No      5174   73.463013
Yes     1869   26.536987

In [10]:
df['SeniorCitizen'] = df['SeniorCitizen'].map({1: 'Yes', 0: 'No'})
df['SeniorCitizen']

0        No
1        No
2        No
3        No
4        No
       ...
7038     No
7039     No
7040     No
7041    Yes
7042     No
Name: SeniorCitizen, Length: 7043, dtype: object

In [11]:
df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})
numeric_features = df.select_dtypes(include=[np.number]).columns.tolist()
numeric_features.remove('Churn')

categorical_features = df.select_dtypes(exclude=[np.number]).columns.tolist()
categorical_features.remove('customerID')
print("Numerical Features:", numeric_features)
print("Categorical Features:", categorical_features)
for col in categorical_features:
    uniques = df[col].unique()
    print(f"\nColumn: {col}")
    print(f"Unique count: {len(uniques)}")
    vc = df[col].value_counts(dropna=False)
    print(vc.head(50))
for col in numeric_features:
    print(f"\nColumn: {col}")
    print(df[col].describe())

Numerical Features: ['tenure', 'MonthlyCharges', 'TotalCharges']
Categorical Features: ['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']

Column: gender
Unique count: 2
gender
Male      3555
Female    3488
Name: count, dtype: int64

Column: SeniorCitizen
Unique count: 2
SeniorCitizen
No     5901
Yes    1142
Name: count, dtype: int64

Column: Partner
Unique count: 2
Partner
No     3641
Yes    3402
Name: count, dtype: int64

Column: Dependents
Unique count: 2
Dependents
No     4933
Yes    2110
Name: count, dtype: int64

Column: PhoneService
Unique count: 2
PhoneService
Yes    6361
No      682
Name: count, dtype: int64

Column: MultipleLines
Unique count: 3
MultipleLines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64

Column: InternetService
Unique count: 3
InternetService
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

Column: OnlineSecurity
Unique count: 3
OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64

Column: OnlineBackup
Unique count: 3
OnlineBackup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64

Column: DeviceProtection
Unique count: 3
DeviceProtection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64

Column: TechSupport
Unique count: 3
TechSupport
No                     3473
Yes                    2044
No internet service    1526
Name: count, dtype: int64

Column: StreamingTV
Unique count: 3
StreamingTV
No                     2810
Yes                    2707
No internet service    1526
Name: count, dtype: int64

Column: StreamingMovies
Unique count: 3
StreamingMovies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64

Column: Contract
Unique count: 3
Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

Column: PaperlessBilling
Unique count: 2
PaperlessBilling
Yes    4171
No     2872
Name: count, dtype: int64

Column: PaymentMethod
Unique count: 4
PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

Column: tenure
count    7043.000000
mean       32.371149
std        24.559481
min         0.000000
25%         9.000000
50%        29.000000
75%        55.000000
max        72.000000
Name: tenure, dtype: float64

Column: MonthlyCharges
count    7043.000000
mean       64.761692
std        30.090047
min        18.250000
25%        35.500000
50%        70.350000
75%        89.850000
max       118.750000
Name: MonthlyCharges, dtype: float64

Column: TotalCharges
count    7043.000000
mean     2279.734304
std      2266.794470
min         0.000000
25%       398.550000
50%      1394.550000
75%      3786.600000
max      8684.800000
Name: TotalCharges, dtype: float64

IMPORTANT TO NOTE: 

SeniorCitizen
Originally: Num (0 and 1)
Changed: Cat (No and Yes)

Churn 
Originally: Cat (No and Yes)
Changed: Num (0 and 1)

TotalCharges
Originally: Cat (Missing Values)
Changed: Numeric (NaN)

In [12]:
Q1 = df[numeric_features].quantile(0.25)
Q3 = df[numeric_features].quantile(0.75)
IQR = Q3 - Q1

outliers = ((df[numeric_features] < (Q1 - 1.5 * IQR)) | 
            (df[numeric_features] > (Q3 + 1.5 * IQR)))
print("Outlier counts per feature:")
print(outliers.sum())

Outlier counts per feature:
tenure            0
MonthlyCharges    0
TotalCharges      0
dtype: int64

In [13]:
## did some feature engineering and saved the cleaned data for modeling
## df.to_csv(r"C:\Users\aashu\OneDrive\Desktop\Churn Prediction\data\cleaned_telco_churn.csv", index=False)
## ^^ code for saving cleaned data
## What I did:
## Total charges - converted to numeric (was non numeric because of missing values) - Changed missing values with 0 - tenure was also 0 for those customers 
# (Makes Sense: No tenure means no charges)
##